# Configuration for markdownlint
# https://github.com/DavidAnson/markdownlint

# Default state for all rules
default: true

# Path to configuration file to extend
extends: null

# MD003/heading-style/header-style - Heading style
MD003:
  style: "atx"

# MD004/ul-style - Unordered list style
MD004:
  style: "dash"

# MD007/ul-indent - Unordered list indentation
MD007:
  indent: 2
  start_indented: false

# MD009/no-trailing-spaces - Trailing spaces
MD009:
  br_spaces: 2
  list_item_empty_lines: false
  strict: false

# MD010/no-hard-tabs - Hard tabs
MD010:
  code_blocks: false

# MD012/no-multiple-blanks - Multiple consecutive blank lines
MD012:
  maximum: 2

# MD013/line-length - Line length
MD013:
  line_length: 120
  heading_line_length: 120
  code_blocks: false
  tables: false
  headings: true
  strict: false
  stern: false

# MD022/blanks-around-headings/blanks-around-headers - Headings should be surrounded by blank lines
MD022:
  lines_above: 1
  lines_below: 1

# MD024/no-duplicate-heading/no-duplicate-header - Multiple headings with the same content
MD024:
  siblings_only: true

# MD025/single-title/single-h1 - Multiple top level headings in the same document
MD025:
  level: 1
  front_matter_title: "^\\s*title\\s*[:=]"

# MD026/no-trailing-punctuation - Trailing punctuation in heading
MD026:
  punctuation: ".,;:!。，；：!"

# MD029/ol-prefix - Ordered list item prefix
MD029:
  style: "ordered"

# MD030/list-marker-space - Spaces after list markers
MD030:
  ul_single: 1
  ol_single: 1
  ul_multi: 1
  ol_multi: 1

# MD033/no-inline-html - Inline HTML
MD033:
  allowed_elements:
    - "br"
    - "details"
    - "summary"
    - "img"
    - "a"
    - "code"
    - "pre"
    - "kbd"
    - "sup"
    - "sub"
    - "p"
    - "i"
    - "input"
    - "span"

# MD034/no-bare-urls - Bare URL used
MD034: true

# MD035/hr-style - Horizontal rule style
MD035:
  style: "---"

# MD036/no-emphasis-as-heading/no-emphasis-as-header - Emphasis used instead of a heading
MD036:
  punctuation: ".,;:!?。，；：！?"

# MD041/first-line-heading/first-line-h1 - First line in file should be a top level heading
MD041:
  level: 1
  front_matter_title: "^\\s*title\\s*[:=]"

# MD042/no-empty-links - No empty links
MD042: true

# MD043/required-headings/required-headers - Required heading structure
MD043: false

# MD044/proper-names - Proper names should have the correct capitalization
MD044:
  names:
    - "JavaScript"
    - "TypeScript"
    - "GitHub"
    - "GitLab"
    - "Rust"
    - "Cargo"
    - "visualvault"
    - "VisualVault"
    - "cargo-nextest"
  code_blocks: false

# MD045/no-alt-text - Images should have alternate text (alt text)
MD045: true

# MD046/code-block-style - Code block style
MD046:
  style: "fenced"

# MD047/single-trailing-newline - Files should end with a single newline character
MD047: true

# MD048/code-fence-style - Code fence style
MD048:
  style: "backtick"

# MD049/emphasis-style - Emphasis style should be consistent
MD049:
  style: "asterisk"

# MD050/strong-style - Strong style should be consistent
MD050:
  style: "asterisk"

# MD051/link-fragments - Link fragments should be valid
MD051: true

# MD052/reference-links-images - Reference links and images should use a label that is defined
MD052: true

# MD053/link-image-reference-definitions - Link and image reference definitions should be needed
MD053: true